services:
  minecraft-fabric:
    container_name: 'minecraft-fabric'
    image: 'ghcr.io/cyerdous/minecraft-fabric:main'
    environment:
      - dedicated_ram=2 # Amount of RAM in GB
      - eula=true
      - level_seed= # Optional
      - level_name= # Optional
      - version_minecraft= # Optional 
      - version_fabric= # Optional
    ports:
      - 25565:25565
    # - 25575:25575 # Optional, allows for remote command execution
    volumes:
      - ${STORAGE}/configs/minecraft:/config
    stdin_open: true
    tty: true