services:
  minecraft-fabric:
    container_name: 'minecraft-server-fabric'
    image: 'cyer/minecraft-server-fabric:latest'
    environment:
      - PGID=1000
      - PUID=1000
      - dedicated_ram=2
      - eula=true
      - TZ=${TIMEZONE}
      - level-seed= #optional
      - version_minecraft= #optional if any of the three are missing we pull the latest appropriate version
      - version_fabric= #optional
    ports:
      - 25565:25565
    volumes:
      - ${STORAGE}/configs/minecraft:/config
    stdin_open: true
    tty: true
      